--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DPG896/InstaHub
build-by-default: true
branches:
- senpai
projects:
  InstaHub:
    path: InstaHub/
    icon: "InstaHub/icon.png"
...
