name: InstaHub
version: 2.2.2
main: DPGD896\Hub\Main
api: 4.0.0
author: DPGNotFound

commands:
  hub:
    usage: /hub
    description: Teleport to Main Lobby
    permission: insta.cmd
    
permissions:
  insta.cmd:
    description: Teleport to Main Lobby
    default: true
