name: InstaHub
version: 2.2.1
main: DPGD896\Hub\Main
api: 4.0.0
author: DENPlayz414502

commands:
  hub:
    usage: /hub
    description: Teleport to Main Lobby
    permission: instahub.command
    
permissions:
  insta.hub:
    description: Teleport to Main Lobby
    default: true
