name: InstaHub
version: 2.1.0
main: DPGD896\Hub\Main
api: 4.0.0
author: DENPlayz414502

commands:
  hub:
    usage: /hub
    description: Teleport to Main Lobby
    permission: insta.hub
    
permissions:
  insta.hub:
    description: Teleport to Main Lobby
    default: true
