---
# Config file of InstaHub

#  ____  ____   ____ 
# |  _ \|  _ \ / ___|
# | | | | |_) | |  _ 
# | |_| |  __/| |_| |
# |____/|_|    \____|
                    

# If you're having problems with this plugin, Contact us on discord https://discord.thedpg.tk

# Lobby
world: "world"

# Messages when a player triggered a command:
title: "Teleported"
subtitle: "To Lobby!"
message-to-player: "Change this on config.yml!"

# Message when an admin typed the command on console:
console-error: "Run this in-game!!"

# End of Config File
---
